/*Creacion de usuarios*/
INSERT INTO users (id, username, email, password, phone)
    VALUES (1, 'edwin estrada', 'prueba1@gmail.com', '123456', '320341');
INSERT INTO users (id, username, email, password, phone)
    VALUES (2, 'Lucas Ramirez', 'prueba2@gmail.com', '12345', '320341');


/*Noticias*/
INSERT INTO news (id,author, content, title)
    VALUES (1,'minambiente', 'La Ley 1715 de 2014 establece normas de transparencia y publicación de información sobre la generación y consumo de energía proveniente de fuentes renovables no convencionales. Las entidades responsables deben proporcionar datos claros y accesibles al público sobre la cantidad de energía generada, la eficiencia de los sistemas y el impacto ambiental1. Para más detalles sobre los requisitos para aplicar a los beneficios ofrecidos por esta ley, puedes consultar la Guía Práctica para la Aplicación de los Incentivos Tributarios de la Ley 1715 de 2014: En el siguiente link: https://shre.ink/gcI5', 'Deducción sobre el impuesto de renta del 50% del valor de la inversión realizada.');
INSERT INTO news (id,author, content, title) 
    VALUES (2, 'larepublica', 'El jueves 5 de diciembre del año en curso Meta Platforms Inc anunció el jueves un acuerdo para comprar créditos verdes de cuatro grandes proyectos de energía solar en Estados Unidos que ayudarán al propietario de Facebook a cumplir sus objetivos de electricidad limpia a medida que aumentan sus necesidades energéticas. Ampliar información: http://surl.li/bddupr', 'Meta Platforms compra créditos de cuatro grandes proyectos solares estadounidenses.');
INSERT INTO news (id,author, content, title)
    VALUES (3, 'Jorge González', 'Tras un riguroso proceso de selección, ocho compañías lograron cumplir con los requisitos exigidos para participar en esta fase. Entre las seleccionadas se encuentran actores nacionales e internacionales como Ecopetrol y Celsia por parte de Colombia, junto con grandes nombres globales como Jan de Nul y Deme de Bélgica, PowerChina International Group Limited, CTG Colombia Holdings de China, Parque Eólico Offshore Vientos Alisios, y CI GMF II Cooperatief del Reino Unido. Ampliar información: http://surl.li/rtuufv', 'Energía eólica offshore en Colombia, estas son las 8 empresas seleccionadas.');
INSERT INTO news (id,author, content, title)
    VALUES (4, 'Lina Quiroga Rubio', 'En una nueva versión del plan de expansión de generación a 2037, la Unidad de Planeación Minero Energética (Upme) proyecta que la capacidad total instalada del sistema de generación tendrá un crecimiento entre 70 y 85 por ciento. Esto significa que la capacidad instalada de Colombia pasará de los 20,3 gigavatios que se tienen actualmente, a entre 34,7 y 37,7 gigavatios. "Desde la Upme presentamos este nuevo Plan de Expansión en Generación, en el cual analizamos las diferentes fuentes de energía disponibles para identificar el mix de generación que más le conviene al país frente a diferentes escenarios, dando señales en términos de diversificación de la matriz energética, seguridad energética y costos futuros", indicó Adrián Correa, director general de la Upme. Ampliar información: http://surl.li/zhitcr', 'En 13 años, 53 % de la energía que se genere en Colombia sería renovable y la térmica caería a mínimos.');
INSERT INTO news (id,author, content, title)
    VALUES (5, 'weforum', 'Las fuentes de energía con cero emisiones de carbono representaron más del 40% de la electricidad generada en el mundo por primera vez en la historia el año pasado, según un nuevo estudio. Dos informes de BloombergNEF muestran que el 14% de esta energía procedió de las fuentes eólica y solar, y que casi el 91% de la capacidad eléctrica añadida a escala mundial procedió de estas fuentes, frente al 6% de los combustibles fósiles. Este impulso está destinado a continuar, con las energías renovables atrayendo 313 000 millones de nuevas inversiones en la primera mitad de 2024. Esta es una cantidad similar al mismo período en 2023. Ampliar información: http://surl.li/fpvvxm', 'La producción global de renovables alcanza un hito y otras noticias sobre energía');
INSERT INTO news (id,author, content, title)
    VALUES (6, 'minenergia', 'Bogotá, 2 de septiembre de 2024. En un trabajo conjunto para impulsar la sostenibilidad y mejorar la calidad de vida de los colombianos, el Ministerio de Minas y Energía, el Ministerio de Vivienda, Ciudad y Territorio y el Fondo Nacional del Ahorro han firmado un memorando de entendimiento que facilitará la financiación de mejoramiento de vivienda con soluciones de energía renovable, especialmente tecnologías fotovoltaicas. Los créditos de mejoramiento de vivienda del FNA incluirán la posibilidad de financiar la adquisición e instalación de paneles solares, contribuyendo al ahorro en costos de la energía y al desarrollo sostenible del país. Ampliar información:http://surl.li/tsiyys', 'El Ministerio de Minas y Energía, el Ministerio de Vivienda, Ciudad y Territorio y el Fondo Nacional del Ahorro se unen para financiar soluciones solares fotovoltaicas a través de créditos de mejoramiento de vivienda.');
INSERT INTO news (id,author, content, title)
    VALUES (7, 'infobae', 'El artículo consiste en analizar si esta posibilidad es viable, de sus costes y beneficios y de los retos que habría que superar para colocar nada más y nada menos que 52.300 millones de paneles solares a lo largo de los 3,2 millones de kilómetros en los que hay autopistas construidas a lo largo del planeta. Estas ‘carreteras solares’ serían una solución a los problemas de espacio que antes se han comentado, permitiendo explotar a otro nivel la energía solar sin estropear zonas naturales. Otro nivel porque, de esos 3,1 teravatios anuales de 2021, se pasaría a tener un potencial de producir casi 17.600. Esta cantidad es cuatro veces la producción de energía de Estados Unidos cada año, y podría compensar cerca del 29% de las emisiones actuales de CO2. Ampliar información: http://surl.li/wvqxnq', 'Las ‘carreteras solares’: la propuesta que podría revolucionar las energías renovables.');
INSERT INTO news (id,author, content, title)
    VALUES (8, 'renovables', 'La energía solar ha experimentado un crecimiento exponencial en las últimas décadas, consolidándose como una de las fuentes de energía renovable más prometedoras y sostenibles. A medida que la demanda global de energía continúa aumentando y la preocupación por el cambio climático se intensifica, las innovaciones tecnológicas en el campo de la energía solar se vuelven cruciales. * Paneles Solares de Perovskita (Eficiencia y bajo costo de producción). La perovskita es un material cristalino que ha demostrado ser extremadamente eficiente en la conversión de la luz solar en electricidad. Los paneles solares de perovskita se destacan por su alta eficiencia y bajo costo de producción en comparación con los paneles solares tradicionales de silicio. * Tecnología de Células Solares en Tandem. Las células solares en tandem combinan dos o más materiales fotovoltaicos para aprovechar diferentes espectros de luz solar. Esta tecnología permite mejorar la eficiencia de conversión al utilizar múltiples capas de materiales que capturan más energía de la luz solar. * Energía Solar Flotante. Las instalaciones solares flotantes, también conocidas como "fotovoltaica flotante", se colocan en cuerpos de agua como lagos, embalses y mares. Esta tecnología ofrece una solución innovadora para superar las limitaciones de espacio en tierra firme. *Fotovoltaica Integrada en Edificios (BIPV). La fotovoltaica integrada en edificios (BIPV) incorpora paneles solares directamente en materiales de construcción, como techos, fachadas y ventanas. Esta integración permite generar energía solar sin necesidad de instalaciones adicionales. Ampliar información: https://shre.ink/gc8l', 'Tecnologías emergentes en la energía solar');
INSERT INTO news (id,author, content, title)
    VALUES (9,'Natgeo' 'El Sol ha cumplido durante miles de años un rol fundamental en la vida humana, desde el aspecto biológico hasta el social. Sin embargo, y ante la creciente crisis climática, el llamado “astro rey” cobra una importancia todavía mayor, ya que apostar por la energía solar podría ser una estrategia muy eficaz para reducir el calentamiento global causado por las emisiones de combustibles fósiles. "Definitivamente, el Sol sale para todos”, comentó Aline Kirsten, vicepresidenta de la Asociación Brasileña de Energía Solar (ABENS) en una videollamada con National Geographic. Kirsten, ingeniera eléctrica y aspirante a doctora en energía solar fotovoltaica por la Universidad Federal de Santa Catarina (UFSC), se dedica a estudiar el tema desde 2017 y es cofundadora de la Red Brasileña de Mujeres en Energía Solar (MESol), una organización civil que actúa por la igualdad de género en el sector de la energía solar. También forma parte del Consejo de la Sociedad Internacional de Energía Solar (ISES, por sus siglas en inglés). Ampliar información: http://surl.li/jxvzto', 'La energía solar y su potencial para ayudar a reducir el calentamiento global');
INSERT INTO news (id,author, content, title)
    VALUES (10, 'Ifad', 'El árido Altiplano boliviano se encuentra a la sombra de los Andes. Aquí, René Soto Vadillo, como sus padres antes que él, solía tener que acarrear agua por varios kilómetros para dar de beber a su rebaño de llamas y alpacas. Por eso, cuando en el marco del Programa de Fortalecimiento Integral de la Cadena de Valor de los Camélidos en el Altiplano Boliviano (Pro‑Camélidos), financiado por el FIDA, se descubrió una masa de agua oculta bajo el suelo seco, René se alegró mucho. Gracias a este programa se instalaron bombas de agua alimentadas por energía solar, que ahora proporcionan agua a su rebaño sin liberar carbono en el delicado ecosistema de alta montaña. Ampliar información:http://surl.li/vrxifs', 'Energía limpia para comunidades rurales prósperas');

/*Comentarios*/
INSERT INTO comment (body, user_id) VALUES ('matt the beast',1);